version: "3.8"

services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: ./
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
      - ./.docker/data/composer:/home/appuser/.composer
      - ./:/var/www
    command: php -S 0.0.0.0:8080
    ports:
      - 8080:8080
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-}
      YII_DEBUG: 'true'
      YII_ENV: ${YII_ENV:-dev}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: "yes"
      AMQP_USER: ${AMQP_USER:-guest}
      AMQP_PASSWORD: ${AMQP_PASSWORD:-guest}
    extra_hosts:
      - host.docker.internal:${HOST_IP:-172.17.0.1}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      amqp:
        condition: service_healthy

  amqp:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD:-guest}
    expose:
      - 5672
    ports:
      - 15673:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 3s
      timeout: 5s
      retries: 3
